[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
peer_protocol = "246swZwvE2QMk2UFGAKYamCexfH5hSfXFrxmHLwZ9sdk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/khayss/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
