import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { DarkModeProvider } from "./LandingPage/DarkMode";
import { TanstackQueryProvider } from "./tanstack-query-provider";
import { ToastContainer } from "react-toastify";
import { XionAbstractionProvider } from "@/components/providers/xion-abstraction.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Peer Protocol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackQueryProvider>
        <DarkModeProvider>
          <XionAbstractionProvider>
            <body className={inter.className}>{children}</body>
          </XionAbstractionProvider>
          <ToastContainer />
        </DarkModeProvider>
      </TanstackQueryProvider>
    </html>
  );
}
