"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { DarkModeProvider } from "./LandingPage/DarkMode";
import { TanstackQueryProvider } from "./tanstack-query-provider";
import { ToastContainer } from "react-toastify";
import { AbstraxionProvider } from "@burnt-labs/abstraxion";

import "@burnt-labs/abstraxion/dist/index.css";
import "@burnt-labs/ui/dist/index.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Peer Protocol",
//   description: "Generated by create next app",
// };

const treasuryConfig = {
  treasury: "xion1c8re5lw7p5490tzawt76xryxec5k6lsr20lr308m8s4f9cyfgr5sadn0y8",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackQueryProvider>
        <DarkModeProvider>
          <AbstraxionProvider config={treasuryConfig}>
            <body className={inter.className}>{children}</body>
          </AbstraxionProvider>
          <ToastContainer />
        </DarkModeProvider>
      </TanstackQueryProvider>
    </html>
  );
}
